---
# main.yml tasks file for ansible-role-docker_handbrake

- name: Fail if task is unsupported
  fail:
    msg: "unsupported task {{ item }}"
  when: item not in handbrake_supported_tasks
  with_items:
    - "{{ run_tasks }}"

- name: Include tasks
  include_tasks: "tasks/{{ item }}.yml"
  with_items:
    - "{{ run_tasks }}"
